In [3]:
A = [1 2; 3 4; 5 6];
B = 10*ones(size(A)) + A;
C = [1 1; 2 2];

In [4]:
A*C

ans =

    5    5
   11   11
   17   17



↓アダマール積 $A \circ B$

In [5]:
A .* B

ans =

   11   24
   39   56
   75   96



In [6]:
A .^ 2

ans =

    1    4
    9   16
   25   36



In [7]:
v = [1; 2; 3]

v =

   1
   2
   3



In [8]:
1 ./ v

ans =

   1.00000
   0.50000
   0.33333



In [9]:
log(v)

ans =

   0.00000
   0.69315
   1.09861



In [10]:
exp(v)

ans =

    2.7183
    7.3891
   20.0855



In [12]:
abs([-1; 1; -10])

ans =

    1
    1
   10



In [17]:
a = [ 1 15 2 0.5]

a =

    1.00000   15.00000    2.00000    0.50000



In [18]:
val = max(a)

val =  15


In [19]:
[val, ind] = max(a)

val =  15
ind =  2


In [20]:
max(A)

ans =

   5   6



In [21]:
a < 3

ans =

  1  0  1  1



In [22]:
find(a < 3)

ans =

   1   3   4



In [23]:
A = magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [26]:
disp(sum(a))
disp(prod(a))
disp(floor(a))
disp(ceil(a))

 18.500
 15
    1   15    2    0
    1   15    2    1


In [27]:
A

A =

   8   1   6
   3   5   7
   4   9   2



In [28]:
max(A, [], 1)

ans =

   8   9   7



In [29]:
max(A, [], 2)

ans =

   8
   7
   9



In [30]:
max(A)

ans =

   8   9   7



In [31]:
max(A(:))

ans =  9


In [32]:
A = magic(9)

A =

   47   58   69   80    1   12   23   34   45
   57   68   79    9   11   22   33   44   46
   67   78    8   10   21   32   43   54   56
   77    7   18   20   31   42   53   55   66
    6   17   19   30   41   52   63   65   76
   16   27   29   40   51   62   64   75    5
   26   28   39   50   61   72   74    4   15
   36   38   49   60   71   73    3   14   25
   37   48   59   70   81    2   13   24   35



In [33]:
sum(A, 1)

ans =

   369   369   369   369   369   369   369   369   369



In [34]:
sum(A, 2)

ans =

   369
   369
   369
   369
   369
   369
   369
   369
   369



In [35]:
sum(sum(A .* eye(9)))

ans =  369


In [36]:
sum(sum(A .* flipud(eye(9))))

ans =  369


In [37]:
eye(9)

ans =

Diagonal Matrix

   1   0   0   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   0   0   1



In [38]:
flipud(eye(9))

ans =

Permutation Matrix

   0   0   0   0   0   0   0   0   1
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   1   0   0   0   0   0   0   0   0

